name: .NET Core CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # 使用 Ubuntu 虛擬機，適合 .NET 專案

    steps:
      # 1️⃣ 下載你的 GitHub Repo 原始碼
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 安裝 .NET 8 SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 3️⃣ 還原專案依賴（nuget 套件）
      - name: Restore dependencies
        run: dotnet restore MyDiarySolution.sln

      # 4️⃣ 執行靜態程式碼格式檢查（等於 `dotnet format --check`）
      - name: Format check
        run: dotnet format DiaryApp/DiaryApp.csproj --verify-no-changes --verbosity diagnostic
        continue-on-error: true  # 格式錯誤時不會中斷流程，但會顯示錯誤

      # 5️⃣ 編譯整個 ASP.NET 
      - name: Build solution
        run: dotnet build MyDiarySolution.sln --no-restore --configuration Debug

      # 6️⃣ 執行單元測試
      - name: Run unit Tests
        run: dotnet test MyDiarySolution.sln --no-build --verbosity normal

      # 7️⃣ 將建置輸出作為 Artifact 上傳（模擬部署用）
      - name: Publish App
        run: dotnet publish DiaryApp/DiaryApp.csproj -c Release -o ./publish

      # 8️⃣ 上傳產出為 Artifact，讓你可以從 GitHub Actions 下載
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: diaryapp-artifact
          path: publish/  # 對應上方輸出路徑
