name: .NET Core CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # 使用 Ubuntu 虛擬機，適合 .NET 專案

    steps:
      # 1️⃣ 下載你的 GitHub Repo 原始碼
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 安裝 .NET SDK（自動抓最新支援 LTS 版）
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      # 3️⃣ 還原專案依賴（nuget 套件）
      - name: Restore dependencies
        run: dotnet restore DiaryApp/DiaryApp.csproj

      # 4️⃣ 執行靜態程式碼格式檢查（等於 `dotnet format --check`）
      - name: Check code formatting
        run: dotnet format DiaryApp/DiaryApp.csproj --verify-no-changes --verbosity diagnostic

      # 5️⃣ 編譯整個 ASP.NET App（Release 模式，不重複還原）
      - name: Build App Project
        run: dotnet build DiaryApp/DiaryApp.csproj --configuration Release --no-restore

      # 6️⃣ 執行測試專案（例如 DiaryApp.Tests）
      - name: Run Tests
        run: dotnet test DiaryApp.Tests/DiaryApp.Tests.csproj --no-build --verbosity normal

      # 7️⃣ 建立發佈檔案（模擬部署用）
      - name: Publish App
        run: dotnet publish DiaryApp/DiaryApp.csproj --configuration Release --no-build --output publish

      # 8️⃣ 上傳產出為 Artifact，讓你可以從 GitHub Actions 下載
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: diaryapp-publish
          path: publish/
